"""
Question : https://www.hackerrank.com/contests/projecteuler/challenges/euler002/problem

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.

"""
#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    fib = [0, 1] 
    even_fibsum = 0
    while fib[-1] < n:
        next_term = fib[-1] + fib[-2]
        fib.append(next_term)
        if next_term % 2 == 0 and next_term < n:
            even_fibsum += next_term
    print(even_fibsum)
